// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project2.Data;

#nullable disable

namespace Project2.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240805204455_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Project2.Models.Actor.GameActor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AttackList")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AttackUnarmed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Attributes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DefenseArmor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("HealthDice")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InventoryId")
                        .HasColumnType("int");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Proficiency")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("GameActor");

                    b.HasDiscriminator().HasValue("GameActor");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Project2.Models.Combats.Combat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActorEnemyId")
                        .HasColumnType("int");

                    b.Property<int>("ActorPlayerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ActorEnemyId")
                        .IsUnique();

                    b.ToTable("Combat");
                });

            modelBuilder.Entity("Project2.Models.Items.Inventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Inventory");
                });

            modelBuilder.Entity("Project2.Models.Items.Item", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("Project2.Models.User.UserPlayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserPlayer");
                });

            modelBuilder.Entity("Project2.Models.Actor.ActorEnemy", b =>
                {
                    b.HasBaseType("Project2.Models.Actor.GameActor");

                    b.HasDiscriminator().HasValue("ActorEnemy");
                });

            modelBuilder.Entity("Project2.Models.Actor.ActorPlayer", b =>
                {
                    b.HasBaseType("Project2.Models.Actor.GameActor");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Experience")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasIndex("UserId");

                    b.HasDiscriminator().HasValue("ActorPlayer");
                });

            modelBuilder.Entity("Project2.Models.Actor.GameActor", b =>
                {
                    b.HasOne("Project2.Models.Items.Item", "item")
                        .WithMany("gameActorItems")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("item");
                });

            modelBuilder.Entity("Project2.Models.Combats.Combat", b =>
                {
                    b.HasOne("Project2.Models.Actor.ActorEnemy", "enemy")
                        .WithOne("combat")
                        .HasForeignKey("Project2.Models.Combats.Combat", "ActorEnemyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project2.Models.Actor.ActorPlayer", "player")
                        .WithOne("combat")
                        .HasForeignKey("Project2.Models.Combats.Combat", "ActorEnemyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("enemy");

                    b.Navigation("player");
                });

            modelBuilder.Entity("Project2.Models.Items.Item", b =>
                {
                    b.HasOne("Project2.Models.Items.Inventory", "inventories")
                        .WithMany("InventoryItems")
                        .HasForeignKey("Id")
                        .HasPrincipalKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("inventories");
                });

            modelBuilder.Entity("Project2.Models.Actor.ActorPlayer", b =>
                {
                    b.HasOne("Project2.Models.User.UserPlayer", "user")
                        .WithMany("userPlayers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("Project2.Models.Items.Inventory", b =>
                {
                    b.Navigation("InventoryItems");
                });

            modelBuilder.Entity("Project2.Models.Items.Item", b =>
                {
                    b.Navigation("gameActorItems");
                });

            modelBuilder.Entity("Project2.Models.User.UserPlayer", b =>
                {
                    b.Navigation("userPlayers");
                });

            modelBuilder.Entity("Project2.Models.Actor.ActorEnemy", b =>
                {
                    b.Navigation("combat");
                });

            modelBuilder.Entity("Project2.Models.Actor.ActorPlayer", b =>
                {
                    b.Navigation("combat");
                });
#pragma warning restore 612, 618
        }
    }
}
